version: "3"

services:
  goapp:
    build: .
    volumes:
      - .:/app

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql
